name: Attach Mod to Release

on:
  release:
    types: [published]

jobs:
  attach-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Extract version from release tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version and archives name in gradle.properties
        run: |
          sed -i "s/mod_version=.*/mod_version=${{ env.VERSION }}/" gradle.properties
          sed -i "s/archives_base_name=.*/archives_base_name=lite2edit-fabric-1.20.4/" gradle.properties

      - name: Build mod
        run: ./gradlew remapJar

      - name: Upload mod to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/lite2edit-fabric-1.20.4-${{ steps.version.outputs.version }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
