FROM jetbrains/qodana-jvm-community:2025.2

# Install Java 17
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean

# Set JAVA_HOME for Java 17 (optional, if needed)
ENV JAVA_17_HOME=/usr/lib/jvm/java-17-openjdk-amd64
