name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  publish-modrinth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft_version: ["1.20.2", "1.20.4", "1.20.5", "1.20.6", "1.21", "1.21.1", "1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9", "1.21.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Extract version from release tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish to Modrinth
        run: |
          ./gradlew modrinth \
            -Pmod_version=${{ steps.version.outputs.version }} \
            -Pminecraft_version=${{ matrix.minecraft_version }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_ID: ${{ secrets.MODRINTH_ID }}
