name: Publish to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        minecraft_version: ["1.20.2", "1.20.4", "1.20.5", "1.20.6", "1.21", "1.21.1", "1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9", "1.21.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Extract version from release tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version and artifact name in gradle.properties
        run: |
          sed -i "s/mod_version=.*/mod_version=${{ env.VERSION }}/" gradle.properties
          sed -i "s/archives_base_name=.*/archives_base_name=lite2edit-fabric-${{ matrix.minecraft_version }}/" gradle.properties

      - name: Build and publish to GitHub Packages for MC ${{ matrix.minecraft_version }}
        run: ./gradlew publish "-Pminecraft_version=${{ matrix.minecraft_version }}"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
