name: Build and Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '0.3'

env:
  JAVA_VERSION: 21

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft_version:
          - '1.20.2'
          - '1.20.4'
          - '1.20.5'
          - '1.20.6'
          - '1.21'
          - '1.21.1'
          - '1.21.3'
          - '1.21.4'
          - '1.21.5'
          - '1.21.6'
          - '1.21.7'
          - '1.21.8'
          - '1.21.9'
          - '1.21.10'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION=${VERSION#v}
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and Publish for Minecraft ${{ matrix.minecraft_version }}
        run: |
          ./gradlew publish \
            -Pmod_version=${{ steps.version.outputs.version }} \
            -Pminecraft_version=${{ matrix.minecraft_version }} \
            --no-daemon \
            --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lite2edit-${{ steps.version.outputs.version }}-mc${{ matrix.minecraft_version }}
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
          retention-days: 30
