name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  build-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        minecraft_version: ["1.20.2", "1.20.4", "1.20.5", "1.20.6", "1.21", "1.21.1", "1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9", "1.21.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Extract version from release tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version in gradle.properties
        run: |
          sed -i "s/mod_version=.*/mod_version=${{ env.VERSION }}/" gradle.properties

      - name: Build mod for MC ${{ matrix.minecraft_version }}
        run: ./gradlew remapJar "-Pminecraft_version=${{ matrix.minecraft_version }}"

      - name: Rename and upload JAR
        run: |
          mv build/libs/Lite2Edit-${{ steps.version.outputs.version }}.jar build/libs/lite2edit-fabric-${{ matrix.minecraft_version }}-${{ steps.version.outputs.version }}.jar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-${{ matrix.minecraft_version }}
          path: build/libs/lite2edit-fabric-${{ matrix.minecraft_version }}-${{ steps.version.outputs.version }}.jar
          retention-days: 1

  publish-modrinth:
    needs: build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from release tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: builds/

      - name: Organize files for publishing
        run: |
          mkdir -p final-builds
          find builds/ -name "*.jar" -exec cp {} final-builds/ \;
          ls -la final-builds/

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ secrets.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: final-builds/*.jar

          name: Lite2Edit ${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
          version-type: release

          changelog-file: CHANGELOG.md

          loaders: |
            fabric

          game-versions: |
            1.20.2
            1.20.4
            1.20.5
            1.20.6
            1.21
            1.21.1
            1.21.3
            1.21.4
            1.21.5
            1.21.6
            1.21.7
            1.21.8
            1.21.9
            1.21.10

          dependencies: |
            fabric-language-kotlin | depends | *
            worldedit | depends | *

          java: |
            21
