name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  publish-modrinth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Extract version from release tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version in gradle.properties
        run: |
          sed -i "s/mod_version=.*/mod_version=${{ env.VERSION }}/" gradle.properties

      - name: Build mod
        run: ./gradlew build

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ secrets.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            build/libs/Lite2Edit-${{ steps.version.outputs.version }}.jar

          name: Lite2Edit ${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
          version-type: release

          changelog: ${{ github.event.release.body }}

          loaders: |
            fabric

          game-versions: |
            1.20.4

          dependencies: |
            fabric-api | depends | *
            fabric-language-kotlin | depends | *
            worldedit | depends | *

          java: |
            21
